[application]
name = "chords"
asset_dir = "assets"

[web.app]
base_path = "chords"
title = "chords"

[web.resource]
style = ["main.css"]
script = []

[web.resource.dev]
script = []

[web.watcher]
watch_path = ["src", "assets"]
reload_html = true
